# Script-mode regression check: no configure, compiler, build or firmware output.
cmake_minimum_required(VERSION 3.16)
set(ENV{IDF_PATH} [=[C:\Users\mati\esp\v5.4.1\esp-idf]=])
function(idf_component_register)
    cmake_parse_arguments(CHECK "" "" "SRCS;INCLUDE_DIRS;PRIV_INCLUDE_DIRS;REQUIRES" ${ARGN})
    if(NOT "hs_crack_crypto.c" IN_LIST CHECK_SRCS)
        message(FATAL_ERROR "Crypto source is not registered")
    endif()
    if(NOT CHECK_PRIV_INCLUDE_DIRS STREQUAL "C:/Users/mati/esp/v5.4.1/esp-idf/components/mbedtls/mbedtls/library")
        message(FATAL_ERROR "Windows IDF path was not normalized: ${CHECK_PRIV_INCLUDE_DIRS}")
    endif()
endfunction()
function(target_compile_definitions)
endfunction()
include("${CMAKE_CURRENT_LIST_DIR}/../main/CMakeLists.txt")
message(STATUS "Windows IDF path and crypto registration checks passed (no build)")
