import {test} from 'node:test';
import assert from 'node:assert/strict';
import {settingsS20} from '../tools/ui_emulator/web/settings-s20.mjs';
const state={tab:3,timeOpen:false,baudOpen:false,status:'',clock:'13:05',clockVisible:true,h24:true,dst:false,show:true,baud:460800,offset:0,now:100,rollers:'2027,1,31,13,5',has:()=>true};
function start(id){const g=settingsS20.find(e=>e.id===id).create();g.start(state);g.setContext({tab:3,visible:true});return g;}
function feed(g,s={}){g.accept({...state,...s,epoch:g.epoch});}
test('date needs fresh native changed rollers, successful write and ticking clock',()=>{const g=start('s20-time');feed(g,{timeOpen:true});feed(g,{timeOpen:true,status:'RTC set: old'});assert.equal(g.step,1);feed(g,{timeOpen:true,status:'RTC set: new',rollers:'2027,1,31,13,6',offset:60000});assert.equal(g.step,2);feed(g,{timeOpen:true,now:100});assert.equal(g.step,2);feed(g,{timeOpen:true,now:101});assert.equal(g.step,3);feed(g);assert.equal(g.complete,true);});
test('invalid calendar cannot advance on old failure or successful normalization',()=>{const g=start('s20-invalid');feed(g,{timeOpen:true});feed(g,{timeOpen:true,status:'Failed to write RTC.'});assert.equal(g.step,1);feed(g,{timeOpen:true,status:'RTC set: normalized',rollers:'2027,2,31,13,5'});assert.equal(g.step,1);feed(g,{timeOpen:true,status:'Failed to write RTC.',rollers:'2027,2,31,13,5'});assert.equal(g.step,2);});
test('unchanged preferences, hidden context and stale epochs cannot progress',()=>{for(const id of ['s20-format','s20-dst','s20-visibility','s20-baud']){const g=start(id);feed(g,{timeOpen:true,baudOpen:true});feed(g,{timeOpen:true,baudOpen:true});assert.equal(g.step,1);g.setContext({tab:3,visible:false});feed(g,{timeOpen:true,baudOpen:true,h24:false,dst:true,show:false,baud:921600});assert.equal(g.step,1);g.setContext({tab:3,visible:true});g.accept({...state,timeOpen:true,h24:false,epoch:g.epoch-1});assert.equal(g.step,1);g.leave();feed(g);assert.equal(g.active,false);}});
test('cancel requires unsaved edit and preserved offset on reopen',()=>{const g=start('s20-cancel');feed(g,{timeOpen:true});feed(g,{timeOpen:true,rollers:'2027,1,31,13,6'});feed(g);assert.equal(g.step,3);feed(g,{timeOpen:true,offset:60000});assert.equal(g.complete,false);feed(g,{timeOpen:true,status:'RTC now: original'});assert.equal(g.step,4);feed(g);assert.equal(g.complete,true);});
test('format must match RTC and DST must shift exactly one hour within RTC precision',()=>{const format=start('s20-format');feed(format,{timeOpen:true});feed(format,{timeOpen:true,h24:false,clock:'01:05'});assert.equal(format.step,1);feed(format,{timeOpen:true,h24:false,clock:'12:01'});assert.equal(format.step,2);const dst=start('s20-dst');feed(dst,{timeOpen:true});feed(dst,{timeOpen:true,dst:true,offset:7200000});assert.equal(dst.step,1);feed(dst,{timeOpen:true,dst:true,offset:3599700});assert.equal(dst.step,2);});

